import { AnimalBiteRecord } from '../types'

export function mapAnimalBiteRecord(r: Record<string, unknown>): AnimalBiteRecord {
  const ageInMonthsRaw = r.ageInMonths ?? r.age_in_months

  return {
    id: String(r.id ?? ''),
    registrationNumber: String(r.registrationNumber ?? ''),
    dateOfVisit: String(r.dateOfVisit ?? ''),
    fullName: String(r.fullName ?? ''),
    address: String(r.address ?? ''),
    contactNumber: String(r.contactNumber ?? ''),
    age: String(r.age ?? ''),
    ageInMonths: ageInMonthsRaw == null || ageInMonthsRaw === '' ? undefined : Number(ageInMonthsRaw),
    gender: String(r.gender ?? ''),
    dateOfBirth: String(r.dateOfBirth ?? ''),
    philhealthMember: String(r.philhealthMember ?? ''),
    philhealthNumber: String(r.philhealthNumber ?? ''),
    allergies: String(r.allergies ?? ''),
    immunocompromisedStatus: String(r.immunocompromisedStatus ?? ''),
    specifyIllness: String(r.specifyIllness ?? ''),
    intakeSteroidsChloroquine: Number(r.intakeSteroidsChloroquine) > 0,
    bp: String(r.bp ?? ''),
    hr: String(r.hr ?? ''),
    rr: String(r.rr ?? ''),
    temp: String(r.temp ?? ''),
    patientWeight: String(r.patientWeight ?? ''),
    bitingAnimal: String(r.bitingAnimal ?? ''),
    bitingAnimalOthers: String(r.bitingAnimalOthers ?? ''),
    ownership: String(r.ownership ?? ''),
    antiRabiesVaccination: String(r.antiRabiesVaccination ?? ''),
    category: String(r.category ?? ''),
    circumstance: String(r.circumstance ?? ''),
    typeOfExposure: String(r.typeOfExposure ?? ''),
    dateOfExposure: String(r.dateOfExposure ?? ''),
    placeOfExposure: String(r.placeOfExposure ?? ''),
    humanArvStatus: String(r.humanArvStatus ?? ''),
    dateLastVaccination: String(r.dateLastVaccination ?? ''),
    biteSiteNotes: String(r.biteSiteNotes ?? ''),
    washingBiteWound: Number(r.washingBiteWound) > 0,
    fullRegimen: Number(r.fullRegimen) > 0,
    booster: Number(r.booster) > 0,
    vaccineGenericName: String(r.vaccineGenericName ?? ''),
    vaccineBrandName: String(r.vaccineBrandName ?? ''),
    vaccineRoute: String(r.vaccineRoute ?? ''),
    day0: String(r.day0 ?? ''),
    day3: String(r.day3 ?? ''),
    day7: String(r.day7 ?? ''),
    day14: String(r.day14 ?? ''),
    day2128: String(r.day2128 ?? r.day21_28 ?? ''),
    animalStatusAfterDay14: String(r.animalStatusAfterDay14 ?? ''),
    erigHrigComputedDose: String(r.erigHrigComputedDose ?? ''),
    erigHrigActualDose: String(r.erigHrigActualDose ?? ''),
    erigHrigDateGiven: String(r.erigHrigDateGiven ?? ''),
    tetanusWoundType: String(r.tetanusWoundType ?? ''),
    tetanusDateLast: String(r.tetanusDateLast ?? ''),
    tetanusToxoid: String(r.tetanusToxoid ?? ''),
    ats: String(r.ats ?? ''),
    diagnosisNotes: String(r.diagnosisNotes ?? ''),
    progressNotes: String(r.progressNotes ?? ''),
    nurseInCharge: String(r.nurseInCharge ?? ''),
    physicianCharge: String(r.physicianCharge ?? ''),
    createdAt: String(r.createdAt ?? ''),
    updatedAt: String(r.updatedAt ?? ''),
  }
}